version: '3'

services:
  mysql:
    image: mysql
    networks:
      - wpnet
    volumes:
      - mysqlvol:/var/lib/mysql
    ports:
      - 3307:3306
      - 33061:33060
    restart: always
    # ignore command if using MySQL 5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=myrootpass
      - MYSQL_DATABASE=wpdb
      - MYSQL_USER=wpuser
      - MYSQL_PASSWORD=mypass

  wp:
    depends_on:
      - mysql
    image: wordpress
    networks:
      - wpnet
    volumes:
      - wpvol:/var/www/html
    ports:
      - 8085:80
    restart: always
    environment:
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_NAME=wpdb
      - WORDPRESS_DB_USER=wpuser
      - WORDPRESS_DB_PASSWORD=mypass

networks:
  wpnet:

volumes:
  mysqlvol:
  wpvol: